### ISSUE TITLE
使用多份send message and wait reply并行触发同一个CSM时，CSM会卡住，且会漏掉一些指令，不报错

### ISSUE THREAD

**Issue by SallyTYT** [NEVSTOP-LAB/Communicable-State-Machine#197]
![image](https://github.com/NEVSTOP-LAB/Communicable-State-Machine/assets/64485819/51666303-4b37-408f-ac4a-78ec5df36622)

**Comment by nevstop** [comment]
能够复现
![image](https://github.com/NEVSTOP-LAB/Communicable-State-Machine/assets/8196752/fb171abf-4623-48a3-8b01-b1b9ea635d6a)

**Comment by SallyTYT** [comment]
> > Post Message 好像也有类似的问题
> 
> Post Message 不检查CSM状态的，只往Queue里面丢信息，所以应该没有这个问题。可能是和 -@ 混用出现的问题。
> 
> 这个 submit 如果在忙碌中的话，SendMessage 的地方不会直接退出，而是等待指定的TMO, 按时销毁回传的Queue. 处理到某个SendMessage 时，会先检查队列有效性，判断是否依然在等待。 PostMessage 无论是否忙碌，都写入队列。

是的，的确跟SendMessage混用了
