### ISSUE TITLE
Supports registering the CSM which the Names is automatically generated

### ISSUE THREAD

**Issue by KivenJia** [NEVSTOP-LAB/Communicable-State-Machine#295]
当前如果这个CSM的名字是自动生成的，这个CSM是不能注册状态的。

**Comment by nevstop** [comment]
![image](https://github.com/user-attachments/assets/6b5c813a-f2f8-48a3-8b7d-b44b9b17b42b)

**Comment by nevstop** [comment]
@KivenJia Fixed.
