### ISSUE TITLE
Tools: Add VI Reference Cases

### ISSUE THREAD

**Issue by KivenJia** [NEVSTOP-LAB/Communicable-State-Machine#311]
[CSM - Add VI Reference Case to CSMs.vi](https://github.com/NEVSTOP-LAB/Communicable-State-Machine/blob/main/src/user.lib/_NEVSTOP/Communicable%20State%20Machine(CSM)/_tool/CSM%20-%20Add%20VI%20Reference%20Case%20to%20CSMs.vi)

需要解决当核心vi "Parse State Queue++.vi" 被二次封装用于特定场景时无法被检索的情况。

**Comment by nevstop** [comment]
可以通过 https://github.com/NEVSTOP-LAB/Communicable-State-Machine/issues/310 这个功能优化，有时候上面有一些新的tunnel时，这个功能不会连接这些tunnel。可以利用这几个helperAPI 完成连线

![image](https://github.com/user-attachments/assets/a5928890-3dee-4693-bee6-a967bf3a950e)
